### PR TITLE
fix Iframe component

### PR DESCRIPTION
**Pull request by Soto92**
removed timeout in loading

### CODE REVIEW

**Comment by brunormferreira** [comment]
Hello @Soto92,

Thanks for your PR.

We implemented that `useEffect` because the frame need to wait some secconds to render, and because of the `Spinner`, after this, we clearing that time with `clearInterval.`

What is your idea when you removed that? 

Cheers,

**Comment by LeonardoCesca** [comment]
@Soto92,

your solution is good but the loader is descentralizated, please create a style for this.

**Comment by Soto92** [comment]
> Hello @Soto92,
> 
> Thanks for your PR.
> 
> We implemented that `useEffect` because the frame need to wait some secconds to render, and because of the `Spinner`, after this, we clearing that time with `clearInterval.`
> 
> Other idea maybe its implement a `Custom Hook` to solve this problem.
> 
> What is your idea when you removed that?
> 
> Cheers,

because it is not a good practice to set a timeout value. What if the loading response is greater than the set, or less? Not to mention that you spend processing just to count the timeout. my implementation loads the div when the url response is ready.

**Comment by Soto92** [comment]
hi guys! I add the iframe style in your component!

**Pull request merged**
